from django.db import models
class AssessmentPack(models.Model):
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=300, blank=True)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self): return self.slug
class AssessmentVersion(models.Model):
    pack = models.ForeignKey(AssessmentPack, on_delete=models.CASCADE, related_name='versions')
    version_number = models.IntegerField()
    status = models.CharField(max_length=20, default='published')
    config_json = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(null=True, blank=True)
    class Meta: unique_together = ('pack', 'version_number')
class AssessmentAttempt(models.Model):
    pack = models.ForeignKey(AssessmentPack, on_delete=models.CASCADE)
    version = models.ForeignKey(AssessmentVersion, on_delete=models.CASCADE)
    user_token = models.CharField(max_length=128, blank=True, null=True)
    status = models.CharField(max_length=20, default='in_progress')
    final_score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    display_score = models.IntegerField(null=True, blank=True)
    band_key = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    paid_at = models.DateTimeField(null=True, blank=True)
    meta_json = models.JSONField(default=dict, blank=True)
class AssessmentAnswer(models.Model):
    attempt = models.ForeignKey(AssessmentAttempt, on_delete=models.CASCADE, related_name='answers')
    question_key = models.CharField(max_length=100)
    raw_value = models.CharField(max_length=100)
    normalized_score = models.DecimalField(max_digits=5, decimal_places=2)
    class Meta: unique_together = ('attempt', 'question_key')
class GeneratedReport(models.Model):
    attempt = models.OneToOneField(AssessmentAttempt, on_delete=models.CASCADE, related_name='report')
    template_key = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    summary = models.TextField()
    content_json = models.JSONField()
    model_name = models.CharField(max_length=100, blank=True)
    prompt_version = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
